version: '3'
services:
  backend:
    build: .
    networks:
      - nodejs_service
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ${PWD}/src:/usr/app/src
    env_file: .env
    restart: on-failure
  db:
    build: ./database/
    hostname: ${POSTGRES_HOST}
    networks:
      - nodejs_service
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  nodejs_service:
    driver: bridge

volumes:
  postgres-data:
